var date_ = document.getElementById("date");
var today = new Date();
date_.innerText = today.toDateString();
var name_ = document.getElementById("name");
name_.innerText = "Aniruddha Bajpai";
var college_ = document.getElementById("college");
college_.innerText = "GLA University";
var rno = document.getElementById("rno");
rno.innerText = "201500092";
